rname: Flutter setup
description: Setup Flutter and install dependencies
runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install dependencies
      run: flutter pub get
